import { defineNuxtModule, extendViteConfig } from "@nuxt/kit";

export default defineNuxtModule({
  meta: {
    name: "ui-thing:optimize-deps",
  },
  setup() {
    extendViteConfig((config) => {
      config.optimizeDeps = config.optimizeDeps || {};
      config.optimizeDeps.include = [
        ...(config.optimizeDeps.include || []),
        "colord",
        "vuedraggable", // CJS
        "@internationalized/date",
        "embla-carousel-autoplay",
        "embla-carousel-vue",
        "qr-code-styling",
        "@vueform/slider",
        "dayjs",
        "yup",
        "@vueup/vue-quill",
        "quill-blot-formatter",
        "date-fns",
        "vee-validate",
        "@vee-validate/yup",
        "zod",
        "v-calendar",
        "lodash-es",
        "vaul-vue",
        "tailwind-merge",
        "tailwind-variants",
        "vue-tippy",
        "motion-v",
        "@tanstack/vue-table",
        "vue-sonner",
        "reka-ui",
        "@faker-js/faker",
        "mermaid",
        "@baybreezy/file-extension-icon",
        "@iconify/utils",
        "@vue/devtools-core",
        "@vue/devtools-kit",
        "maska/vue",
        "@vueuse/integrations/useFuse",
        "@shikijs/engine-oniguruma",
        "@shikijs/engine-javascript",
        "@shikijs/core",
        "@shikijs/transformers",
        "@shikijs/langs/json",
        "@shikijs/langs/javascript",
        "@shikijs/langs/typescript",
        "@shikijs/langs/css",
        "@shikijs/langs/html",
        "@shikijs/langs/markdown",
        "@shikijs/langs/yaml",
        "@shikijs/langs/vue",
        "@shikijs/langs/vue-html",
        "@shikijs/langs/shellscript",
        "@shikijs/langs/svelte",
        "@shikijs/langs/tsx",
        "@shikijs/langs/jsx",
        "@shikijs/langs/prisma",
        "@shikijs/langs/sql",
        "@shikijs/langs/docker",
        "@shikijs/langs/python",
        "@shikijs/themes/github-light",
        "@shikijs/themes/github-dark",
        "shiki/wasm",
        "vue-currency-input",
        "datatables.net",
        "datatables.net-buttons-dt",
        "datatables.net-buttons/js/buttons.colVis.mjs",
        "datatables.net-buttons/js/buttons.html5.mjs",
        "datatables.net-buttons/js/buttons.print.mjs",
        "datatables.net-colreorder-dt",
        "datatables.net-fixedcolumns-dt",
        "datatables.net-fixedheader-dt",
        "datatables.net-responsive-dt",
        "datatables.net-searchbuilder-dt",
        "datatables.net-select-dt",
        "datatables.net-vue3",
        "jszip", // CJS
      ];
    });
  },
});
