/**@type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      typography: () => ({
        DEFAULT: {
          css: {
            "--tw-prose-body": "var(--color-foreground)",
            "--tw-prose-headings": "var(--color-foreground)",
            "--tw-prose-lead": "var(--color-muted-foreground)",
            "--tw-prose-links": "var(--color-foreground)",
            "--tw-prose-bold": "var(--color-foreground)",
            "--tw-prose-counters": "var(--color-muted-foreground)",
            "--tw-prose-bullets": "--alpha(var(--color-primary) / 50%)",
            "--tw-prose-hr": "var(--color-border)",
            "--tw-prose-quotes": "var(--color-foreground)",
            "--tw-prose-quote-borders": "var(--color-border)",
            "--tw-prose-captions": "var(--color-muted-foreground)",
            "--tw-prose-kbd": "var(--color-foreground)",
            "--tw-prose-kbd-shadows": "var(--color-foreground)",
            "--tw-prose-code": "var(--color-foreground)",
            "--tw-prose-pre-code": "var(--color-background)",
            "--tw-prose-pre-bg": "var(--color-code)",
            "--tw-prose-th-borders": "var(--color-border)",
            "--tw-prose-td-borders": "var(--color-border)",
            "--tw-prose-invert-body": "var(--color-foreground)",
            "--tw-prose-invert-headings": "var(--color-foreground)",
            "--tw-prose-invert-lead": "var(--color-muted-foreground)",
            "--tw-prose-invert-links": "var(--color-foreground)",
            "--tw-prose-invert-bold": "var(--color-foreground)",
            "--tw-prose-invert-counters": "var(--color-muted-foreground)",
            "--tw-prose-invert-bullets": "--alpha(var(--color-primary) / 50%)",
            "--tw-prose-invert-hr": "var(--color-border)",
            "--tw-prose-invert-quotes": "var(--color-foreground)",
            "--tw-prose-invert-quote-borders": "var(--color-border)",
            "--tw-prose-invert-captions": "var(--color-muted-foreground)",
            "--tw-prose-invert-kbd": "var(--color-foreground)",
            "--tw-prose-invert-kbd-shadows": "var(--color-foreground)",
            "--tw-prose-invert-code": "var(--color-foreground)",
            "--tw-prose-invert-pre-code": "var(--color-foreground)",
            "--tw-prose-invert-pre-bg": "var(--color-code)",
            "--tw-prose-invert-th-borders": "var(--color-border)",
            "--tw-prose-invert-td-borders": "var(--color-border)",
            "code::before": {
              content: "",
            },
            "code::after": {
              content: "",
            },
          },
        },
      }),
    },
  },
};
