/**
 * Canonical UI Thing component requirements keyed by block path. Generated automatically - do not
 * edit manually.
 */
export default {
  "About/BlockAbout1": "container",
  "About/BlockAbout10": "badge card",
  "About/BlockAbout11": "avatar card",
  "About/BlockAbout12": "badge card",
  "About/BlockAbout13": "badge button",
  "About/BlockAbout14": "badge button card",
  "About/BlockAbout15": "badge card",
  "About/BlockAbout16": "button card",
  "About/BlockAbout17": "badge",
  "About/BlockAbout18": "button card collapsible",
  "About/BlockAbout19": "button card vee-input vee-textarea",
  "About/BlockAbout2": "avatar",
  "About/BlockAbout20": "avatar badge button card",
  "About/BlockAbout3": "badge",
  "About/BlockAbout4": "",
  "About/BlockAbout5": "card",
  "About/BlockAbout6": "",
  "About/BlockAbout7": "avatar badge card",
  "About/BlockAbout8": "border-beam card",
  "About/BlockAbout9": "",
  "Banner/BlockBanner1": "button container vee-input",
  "Banner/BlockBanner10": "button",
  "Banner/BlockBanner2": "button container",
  "Banner/BlockBanner3": "button container",
  "Banner/BlockBanner4": "button container",
  "Banner/BlockBanner5": "button container",
  "Banner/BlockBanner6": "badge button",
  "Banner/BlockBanner7": "button container separator",
  "Banner/BlockBanner8": "badge button",
  "Banner/BlockBanner9": "button container",
  "Career/BlockCareer1": "badge button container",
  "Career/BlockCareer2": "badge button container",
  "Career/BlockCareer3": "badge button container",
  "Career/BlockCareer4": "badge button card container divider tabs",
  "Career/BlockCareer5": "badge button card container vee-input",
  "Career/BlockCareer6": "accordion badge button card container separator",
  "Chart/BlockChartBar.client": "apexcharts",
  "Chart/BlockChartBubble.client": "apexcharts",
  "Chart/BlockChartDonut.client": "apexcharts",
  "Chart/BlockChartLine.client": "apexcharts",
  "Chart/BlockChartPie.client": "apexcharts",
  "Chart/BlockChartRadar.client": "apexcharts",
  "Chart/BlockChartRadialBar.client": "apexcharts",
  "CTA/BlockCTA1": "button container",
  "CTA/BlockCTA2": "button container",
  "CTA/BlockCTA3": "button container",
  "CTA/BlockCTA4": "button container",
  "CTA/BlockCTA5": "button container",
  "CTA/BlockCTA6": "button container",
  "CTA/BlockCTA7": "badge button container input",
  "CTA/BlockCTA8": "button card container",
  "CTA/BlockCTA9": "avatar button card container",
  "Dashboards/BlockDashboards1":
    "alert-dialog apexcharts avatar avatar-label-group badge button card checkbox container datepicker dropdown-menu gradient-divider popover rating sheet tabs tanstacktable vee-input",
  "Dashboards/BlockDashboards10":
    "apexcharts avatar badge button button-group command container dialog dropdown-menu kbd popover toggle-group tooltip",
  "Dashboards/BlockDashboards11":
    "apexcharts avatar badge button button-group checkbox command container datepicker dialog dropdown-menu kbd popover radio-group tooltip",
  "Dashboards/BlockDashboards12":
    "apexcharts avatar badge button button-group checkbox command container datepicker dialog dropdown-menu kbd pagination popover switch tanstacktable tooltip vee-input",
  "Dashboards/BlockDashboards13":
    "apexcharts avatar badge button button-group card checkbox command container credit-card datepicker dialog dropdown-menu kbd popover progress tooltip vee-input vee-select",
  "Dashboards/BlockDashboards2":
    "apexcharts avatar badge button container dropdown-menu fancy-icon gradient-divider popover tabs vee-input",
  "Dashboards/BlockDashboards3":
    "alert-dialog apexcharts avatar badge button card checkbox command container dropdown-menu gradient-divider kbd popover select sheet tabs tanstacktable toggle-group vee-input",
  "Dashboards/BlockDashboards4":
    "alert-dialog apexcharts avatar badge button card checkbox command container dropdown-menu gradient-divider kbd popover select sheet tabs tanstacktable vee-input",
  "Dashboards/BlockDashboards5":
    "alert-dialog apexcharts avatar avatar-label-group badge button card checkbox command container dropdown-menu gradient-divider kbd pagination popover select sheet tabs tanstacktable vee-input",
  "Dashboards/BlockDashboards6":
    "alert-dialog apexcharts avatar badge button card checkbox command container dialog dropdown-menu kbd pagination popover sheet tanstacktable tooltip vee-input vee-select",
  "Dashboards/BlockDashboards7":
    "alert-dialog apexcharts avatar badge button card checkbox command container dialog dropdown-menu kbd pagination popover sheet tanstacktable tooltip vee-input vee-select",
  "Dashboards/BlockDashboards8":
    "alert-dialog apexcharts avatar badge button card checkbox command container dropdown-menu kbd pagination popover sheet tanstacktable tooltip vee-input vee-select",
  "Dashboards/BlockDashboards9":
    "alert-dialog apexcharts avatar badge button button-group card checkbox command container dropdown-menu input kbd pagination popover sheet tanstacktable tooltip vee-input vee-select",
  "App/EmptyState/BlockAppEmptyState1": "button container fancy-icon",
  "App/EmptyState/BlockAppEmptyState2": "button",
  "App/EmptyState/BlockAppEmptyState3": "button",
  "App/EmptyState/BlockAppEmptyState4": "border-beam button card",
  "App/EmptyState/BlockAppEmptyState5": "button",
  "App/EmptyState/BlockAppEmptyState6": "border-beam button",
  "App/EmptyState/BlockAppEmptyState7": "card",
  "App/EmptyState/BlockAppEmptyState8": "button gradient-divider",
  "Error/BlockError": "button",
  "Error/BlockError5": "button",
  "Error/BlockError6": "button card",
  "Error/BlockError7": "button",
  "Error/BlockError8": "badge button card",
  "Error/BlockError9": "button card input",
  "Error/BlockErrorCentered": "button",
  "Error/BlockErrorImage": "button",
  "Error/BlockErrorLinks": "button",
  "FAQ/BlockFAQ1": "button container",
  "FAQ/BlockFAQ2": "button container",
  "FAQ/BlockFAQ3": "accordion button container",
  "FAQ/BlockFAQ4": "accordion button container tabs vee-input",
  "FAQ/BlockFAQ5": "badge button card container vee-input",
  "FAQ/BlockFAQ6": "badge button container",
  "FAQ/BlockFAQ7": "button card container",
  "Feature/BlockFeature1": "container",
  "Feature/BlockFeature10": "badge container",
  "Feature/BlockFeature11": "badge container",
  "Feature/BlockFeature12": "container tabs",
  "Feature/BlockFeature13": "card container",
  "Feature/BlockFeature14": "badge button container",
  "Feature/BlockFeature15": "button card container",
  "Feature/BlockFeature16": "badge container",
  "Feature/BlockFeature17": "badge button container",
  "Feature/BlockFeature18": "button container",
  "Feature/BlockFeature19": "badge card container",
  "Feature/BlockFeature2": "button container",
  "Feature/BlockFeature20": "button container",
  "Feature/BlockFeature3": "container",
  "Feature/BlockFeature4": "container",
  "Feature/BlockFeature5": "container",
  "Feature/BlockFeature6": "container",
  "Feature/BlockFeature7": "container",
  "Feature/BlockFeature8": "container",
  "Feature/BlockFeature9": "badge container",
  "Footer/BlockFooter1": "container",
  "Footer/BlockFooter10": "button container",
  "Footer/BlockFooter11": "container",
  "Footer/BlockFooter12": "button container",
  "Footer/BlockFooter13": "container",
  "Footer/BlockFooter14": "container",
  "Footer/BlockFooter15": "container",
  "Footer/BlockFooter16": "button container divider",
  "Footer/BlockFooter2": "container",
  "Footer/BlockFooter3": "button container vee-input",
  "Footer/BlockFooter4": "button container vee-input",
  "Footer/BlockFooter5": "button container vee-input",
  "Footer/BlockFooter6": "button container",
  "Footer/BlockFooter7": "container",
  "Footer/BlockFooter8": "container",
  "Footer/BlockFooter9": "container",
  "ForgotPassword/BlockForgotPassword": "button vee-input",
  "ForgotPassword/BlockForgotPassword2": "button card divider vee-input",
  "ForgotPassword/BlockForgotPassword3": "button vee-input",
  "ForgotPassword/BlockForgotPasswordSuccess": "button",
  "ForgotPassword/BlockTwoStepVerification": "button card vee-input",
  "App/Header/BlockAppHeader1": "avatar breadcrumbs button container divider",
  "App/Header/BlockAppHeader10": "badge button container scroll-area tabs",
  "App/Header/BlockAppHeader2": "avatar button container",
  "App/Header/BlockAppHeader3": "button container divider",
  "App/Header/BlockAppHeader4": "badge button container divider",
  "App/Header/BlockAppHeader5": "breadcrumbs button container dropdown-menu scroll-area tabs",
  "App/Header/BlockAppHeader6": "avatar button container separator tabs",
  "App/Header/BlockAppHeader7": "avatar badge button container divider separator",
  "App/Header/BlockAppHeader8": "button container dropdown-menu separator",
  "App/Header/BlockAppHeader9": "button container separator vee-input",
  "Contact/Header/BlockContactHeader1": "button container vee-input vee-textarea",
  "Contact/Header/BlockContactHeader2": "button container vee-input vee-textarea",
  "Contact/Header/BlockContactHeader3": "button container vee-input vee-textarea",
  "Contact/Header/BlockContactHeader4": "container",
  "Contact/Header/BlockContactHeader5": "container",
  "Contact/Header/BlockContactHeader6": "avatar badge button card container vee-input vee-textarea",
  "Contact/Header/BlockContactHeader7": "accordion button card container vee-input vee-textarea",
  "Contact/Header/BlockContactHeader8": "button card container divider vee-input vee-textarea",
  "Contact/Header/BlockContactHeader9":
    "badge button card container vee-checkbox vee-input vee-textarea",
  "HeaderSection/BlockHeaderSection1": "container",
  "HeaderSection/BlockHeaderSection10": "container vee-input",
  "HeaderSection/BlockHeaderSection11": "container",
  "HeaderSection/BlockHeaderSection12": "button container",
  "HeaderSection/BlockHeaderSection13": "badge container tabs",
  "HeaderSection/BlockHeaderSection14": "button container vee-input",
  "HeaderSection/BlockHeaderSection15": "container vee-input",
  "HeaderSection/BlockHeaderSection2": "button container",
  "HeaderSection/BlockHeaderSection3": "badge container tabs",
  "HeaderSection/BlockHeaderSection4": "button container vee-input",
  "HeaderSection/BlockHeaderSection5": "container vee-input",
  "HeaderSection/BlockHeaderSection6": "container",
  "HeaderSection/BlockHeaderSection7": "button container",
  "HeaderSection/BlockHeaderSection8": "badge container tabs",
  "HeaderSection/BlockHeaderSection9": "button container vee-input",
  "Hero/BlockHero1": "badge button vee-input",
  "Hero/BlockHero10": "button container vee-input",
  "Hero/BlockHero11": "badge button container",
  "Hero/BlockHero2": "badge button",
  "Hero/BlockHero3": "animated-tooltip button vee-input",
  "Hero/BlockHero4": "button container",
  "Hero/BlockHero5": "animated-tooltip button container vee-input",
  "Hero/BlockHero6": "animated-tooltip button container vee-input",
  "Hero/BlockHero7": "badge button container",
  "Hero/BlockHero8": "badge button container",
  "Hero/BlockHero9": "button container",
  "Login/BlockLoginCentered": "button divider vee-checkbox vee-input",
  "Login/BlockLoginCompact": "button vee-input",
  "Login/BlockLoginMinimal": "button vee-input",
  "Login/BlockLoginSimple": "button vee-input",
  "Login/BlockLoginSimpleCard": "button vee-input",
  "Login/BlockLoginSimpleRemember": "button vee-checkbox vee-input",
  "Login/BlockLoginSimpleSocial": "button divider vee-input",
  "Login/BlockLoginSimpleSocial2": "button divider vee-input",
  "Login/BlockLoginSimpleSocialImage": "button divider vee-input",
  "Login/BlockLoginTwoColumn": "button divider vee-checkbox vee-input",
  "Metric/BlockMetric1": "container",
  "Metric/BlockMetric10": "badge container",
  "Metric/BlockMetric2": "container",
  "Metric/BlockMetric3": "button container",
  "Metric/BlockMetric4": "container",
  "Metric/BlockMetric5": "container",
  "Metric/BlockMetric6": "container",
  "Metric/BlockMetric7": "container",
  "Metric/BlockMetric8": "container",
  "Metric/BlockMetric9": "container",
  "Navigation/BlockNavigation1":
    "button collapsible container gradient-divider navigation-menu scroll-area sheet",
  "Navigation/BlockNavigation2":
    "button collapsible container gradient-divider navigation-menu scroll-area sheet",
  "Navigation/BlockNavigation3":
    "button collapsible container gradient-divider navigation-menu scroll-area sheet",
  "Navigation/BlockNavigation4":
    "button collapsible container gradient-divider navigation-menu scroll-area sheet",
  "Newsletter/BlockNewsletter1": "button container vee-input",
  "Newsletter/BlockNewsletter2": "button container vee-input",
  "Newsletter/BlockNewsletter3": "badge button container vee-input",
  "Newsletter/BlockNewsletter4": "button card container vee-input",
  "Newsletter/BlockNewsletter5": "button card checkbox container vee-input",
  "Newsletter/BlockNewsletter6": "button container vee-input",
  "Newsletter/BlockNewsletter7": "button card container vee-input",
  "OTP/BlockOTPVerification": "button vee-pin-input",
  "OTP/BlockOTPVerification2": "button card divider vee-pin-input",
  "Blog/Page/BlockBlogPage1": "avatar badge container tabs",
  "Blog/Page/BlockBlogPage2": "avatar badge container vee-input",
  "Blog/Page/BlockBlogPage3": "avatar badge button container vee-input",
  "Blog/Page/BlockBlogPage4": "avatar badge button container divider vee-input",
  "Blog/Page/BlockBlogPage5": "avatar badge button card container dropdown-menu separator",
  "Blog/Page/BlockBlogPage6": "avatar badge button card container divider pagination tabs",
  "Blog/Post/BlockBlogPostCard1": "avatar",
  "Blog/Post/BlockBlogPostCard2": "avatar badge",
  "Blog/Post/BlockBlogPostCard3": "badge",
  "Blog/Post/BlockBlogPostCard4": "avatar",
  "Blog/Post/BlockBlogPostCard5": "avatar badge",
  "Blog/Post/BlockBlogPostCard6": "avatar badge button",
  "Blog/Post/BlockBlogPostCard7": "avatar badge button",
  "Blog/Post/BlockBlogPostCard8": "avatar badge button",
  "Blog/Post/BlockBlogPostCard9": "avatar badge divider",
  "Pricing/BlockPricing1": "button card container",
  "Pricing/BlockPricing2": "button card container",
  "Pricing/BlockPricing3": "badge button card container tabs",
  "Pricing/BlockPricing4": "badge button container tabs",
  "Pricing/BlockPricing5": "badge button container",
  "Pricing/BlockPricing6": "badge button container",
  "Pricing/BlockPricing7": "badge button container switch",
  "Pricing/BlockPricing8": "button container",
  "Pricing/BlockPricing9": "badge button container switch",
  "ResetPassword/BlockResetPassword": "button vee-input",
  "ResetPassword/BlockResetPassword2": "button card vee-input",
  "Blog/Section/BlockBlogSection1": "avatar button container",
  "Blog/Section/BlockBlogSection2": "badge button container",
  "Blog/Section/BlockBlogSection3": "avatar container",
  "Blog/Section/BlockBlogSection4": "avatar badge container",
  "Blog/Section/BlockBlogSection5": "avatar badge button card container tabs",
  "Blog/Section/BlockBlogSection6": "avatar badge button card container divider input separator",
  "Blog/Section/BlockBlogSection7": "avatar badge button card container",
  "Blog/Section/BlockBlogSection8": "avatar badge button card container divider scroll-area",
  "App/Sidebar/BlockAppSidebar1":
    "avatar button collapsible divider progress scroll-area tooltip vee-input",
  "App/Sidebar/BlockAppSidebar2": "avatar button divider progress scroll-area tooltip vee-input",
  "App/Sidebar/BlockAppSidebar3": "avatar button divider scroll-area",
  "App/Sidebar/BlockAppSidebar4": "avatar badge button dropdown-menu scroll-area vee-input",
  "App/Sidebar/BlockAppSidebar5":
    "avatar badge border-beam button collapsible dropdown-menu progress scroll-area",
  "App/Sidebar/BlockAppSidebar6":
    "avatar button divider dropdown-menu scroll-area tooltip vee-input",
  "App/Sidebar/BlockAppSidebar7": "avatar button divider dropdown-menu scroll-area tabs vee-input",
  "Sidebar/BlockSidebar01": "breadcrumbs divider dropdown-menu label navbar placeholder sidebar",
  "Sidebar/BlockSidebar02":
    "breadcrumbs collapsible divider dropdown-menu label navbar placeholder sidebar",
  "Sidebar/BlockSidebar03": "breadcrumbs divider dropdown-menu label navbar placeholder sidebar",
  "Sidebar/BlockSidebar04": "breadcrumbs divider dropdown-menu navbar placeholder sidebar",
  "Sidebar/BlockSidebar05":
    "breadcrumbs collapsible divider dropdown-menu label navbar placeholder sidebar",
  "Sidebar/BlockSidebar06":
    "breadcrumbs button card divider dropdown-menu label navbar placeholder sidebar",
  "Sidebar/BlockSidebar07":
    "avatar breadcrumbs collapsible divider dropdown-menu label navbar placeholder sidebar",
  "Sidebar/BlockSidebar08":
    "avatar breadcrumbs collapsible divider dropdown-menu label navbar placeholder sidebar",
  "Sidebar/BlockSidebar09":
    "avatar breadcrumbs divider dropdown-menu label navbar placeholder sidebar switch",
  "Sidebar/BlockSidebar10":
    "breadcrumbs button collapsible divider dropdown-menu placeholder popover sidebar",
  "Sidebar/BlockSidebar11": "breadcrumbs divider placeholder sidebar",
  "Sidebar/BlockSidebar12":
    "avatar breadcrumbs collapsible datepicker dropdown-menu placeholder sidebar",
  "Sidebar/BlockSidebar13": "breadcrumbs button dialog placeholder sidebar",
  "Sidebar/BlockSidebar14": "breadcrumbs placeholder sidebar",
  "Sidebar/BlockSidebarCollapsibleSideGroup": "collapsible container navbar sidebar",
  "Sidebar/BlockSidebarControlled": "button container navbar placeholder sidebar",
  "Sidebar/BlockSidebarFirstSidebar": "container navbar sidebar",
  "Sidebar/BlockSidebarFooter": "container dropdown-menu navbar sidebar",
  "Sidebar/BlockSidebarHeader": "container dropdown-menu navbar sidebar",
  "Sidebar/BlockSidebarSidebarGroupAction": "container navbar sidebar",
  "Sidebar/BlockSidebarSidebarMenuAction": "container dropdown-menu navbar sidebar",
  "Sidebar/BlockSidebarSidebarMenuBadge": "container navbar sidebar",
  "Sidebar/BlockSidebarSidebarMenuSub": "container navbar sidebar",
  "Sidebar/BlockSidebarSidebarMenuSubCollapsible": "collapsible container navbar sidebar",
  "Sidebar/BlockSidebarSidebarRail": "sidebar",
  "SignUp/BlockSignUp": "button vee-input",
  "SignUp/BlockSignUpCard": "button vee-input",
  "SignUp/BlockSignUpCentered": "button divider vee-checkbox vee-input",
  "SignUp/BlockSignUpCompact": "button vee-input",
  "SignUp/BlockSignUpImage": "button divider vee-input",
  "SignUp/BlockSignUpMinimal": "button vee-input",
  "SignUp/BlockSignUpPasswordMeter": "button vee-input",
  "SignUp/BlockSignUpSocial": "button divider vee-input",
  "SignUp/BlockSignUpTwoColumn": "button divider vee-checkbox vee-input",
  "SocialProof/BlockSocialProof1": "container",
  "SocialProof/BlockSocialProof2": "container",
  "SocialProof/BlockSocialProof3": "container",
  "SocialProof/BlockSocialProof4": "avatar card container",
  "SocialProof/BlockSocialProof5": "container",
  "App/Stats/BlockAppStats1": "badge button card dropdown-menu fancy-icon",
  "App/Stats/BlockAppStats10": "card progress",
  "App/Stats/BlockAppStats2": "card",
  "App/Stats/BlockAppStats3": "badge card progress",
  "App/Stats/BlockAppStats4": "badge card",
  "App/Stats/BlockAppStats5": "button card dropdown-menu",
  "App/Stats/BlockAppStats6": "card fancy-icon separator",
  "App/Stats/BlockAppStats7": "card",
  "App/Stats/BlockAppStats8": "button card",
  "App/Stats/BlockAppStats9": "avatar badge button card chip",
  "Blog/Subscribe/BlockBlogSubscribe1": "button card vee-input",
  "Blog/Subscribe/BlockBlogSubscribe2": "button card vee-input",
  "Blog/Subscribe/BlockBlogSubscribe3": "button card vee-input",
  "Blog/Subscribe/BlockBlogSubscribe4": "badge button card vee-input",
  "Blog/Subscribe/BlockBlogSubscribe5": "button card vee-input",
  "Blog/Subscribe/BlockBlogSubscribe6": "button card separator vee-input",
  "Blog/Subscribe/BlockBlogSubscribe7": "badge button card vee-input",
  "Team/BlockTeam1": "avatar container",
  "Team/BlockTeam2": "avatar container",
  "Team/BlockTeam3": "avatar button container",
  "Team/BlockTeam4": "card container",
  "Team/BlockTeam5": "button container",
  "Team/BlockTeam6": "avatar container",
  "Testimony/BlockTestimony1": "avatar container",
  "Testimony/BlockTestimony2": "avatar container",
  "Testimony/BlockTestimony3": "container",
  "Testimony/BlockTestimony4": "container",
  "Testimony/BlockTestimony5": "avatar container",
  "Testimony/BlockTestimony6": "avatar container",
  "Testimony/BlockTestimony7": "avatar container",
  "Testimony/BlockTestimony8": "avatar container",
  "Tiptap/BlockTiptap1": "button container separator toggle tooltip",
} as const;
