export const TYPESET_FONTS = [
  {
    id: "geist-sans",
    label: "Geist",
    family: "Geist",
    type: "sans",
    value: "'Geist', sans-serif",
    cssVar: "--font-geist-sans",
  },
  {
    id: "inter",
    label: "Inter",
    family: "Inter",
    type: "sans",
    value: "'Inter', sans-serif",
    cssVar: "--font-inter",
  },
  {
    id: "noto-sans",
    label: "Noto Sans",
    family: "Noto Sans",
    type: "sans",
    value: "'Noto Sans', sans-serif",
    cssVar: "--font-noto-sans",
  },
  {
    id: "nunito-sans",
    label: "Nunito Sans",
    family: "Nunito Sans",
    type: "sans",
    value: "'Nunito Sans', sans-serif",
    cssVar: "--font-nunito-sans",
  },
  {
    id: "figtree",
    label: "Figtree",
    family: "Figtree",
    type: "sans",
    value: "'Figtree', sans-serif",
    cssVar: "--font-figtree",
  },
  {
    id: "roboto",
    label: "Roboto",
    family: "Roboto",
    type: "sans",
    value: "'Roboto', sans-serif",
    cssVar: "--font-roboto",
  },
  {
    id: "raleway",
    label: "Raleway",
    family: "Raleway",
    type: "sans",
    value: "'Raleway', sans-serif",
    cssVar: "--font-raleway",
  },
  {
    id: "dm-sans",
    label: "DM Sans",
    family: "DM Sans",
    type: "sans",
    value: "'DM Sans', sans-serif",
    cssVar: "--font-dm-sans",
  },
  {
    id: "public-sans",
    label: "Public Sans",
    family: "Public Sans",
    type: "sans",
    value: "'Public Sans', sans-serif",
    cssVar: "--font-public-sans",
  },
  {
    id: "outfit",
    label: "Outfit",
    family: "Outfit",
    type: "sans",
    value: "'Outfit', sans-serif",
    cssVar: "--font-outfit",
  },
  {
    id: "oxanium",
    label: "Oxanium",
    family: "Oxanium",
    type: "sans",
    value: "'Oxanium', sans-serif",
    cssVar: "--font-oxanium",
  },
  {
    id: "manrope",
    label: "Manrope",
    family: "Manrope",
    type: "sans",
    value: "'Manrope', sans-serif",
    cssVar: "--font-manrope",
  },
  {
    id: "space-grotesk",
    label: "Space Grotesk",
    family: "Space Grotesk",
    type: "sans",
    value: "'Space Grotesk', sans-serif",
    cssVar: "--font-space-grotesk",
  },
  {
    id: "montserrat",
    label: "Montserrat",
    family: "Montserrat",
    type: "sans",
    value: "'Montserrat', sans-serif",
    cssVar: "--font-montserrat",
  },
  {
    id: "ibm-plex-sans",
    label: "IBM Plex Sans",
    family: "IBM Plex Sans",
    type: "sans",
    value: "'IBM Plex Sans', sans-serif",
    cssVar: "--font-ibm-plex-sans",
  },
  {
    id: "source-sans-3",
    label: "Source Sans 3",
    family: "Source Sans 3",
    type: "sans",
    value: "'Source Sans 3', sans-serif",
    cssVar: "--font-source-sans-3",
  },
  {
    id: "instrument-sans",
    label: "Instrument Sans",
    family: "Instrument Sans",
    type: "sans",
    value: "'Instrument Sans', sans-serif",
    cssVar: "--font-instrument-sans",
  },
  {
    id: "jetbrains-mono",
    label: "JetBrains Mono",
    family: "JetBrains Mono",
    type: "mono",
    value: "'JetBrains Mono', monospace",
    cssVar: "--font-jetbrains-mono",
  },
  {
    id: "geist-mono",
    label: "Geist Mono",
    family: "Geist Mono",
    type: "mono",
    value: "'Geist Mono', monospace",
    cssVar: "--font-geist-mono",
  },
  {
    id: "noto-serif",
    label: "Noto Serif",
    family: "Noto Serif",
    type: "serif",
    value: "'Noto Serif', serif",
    cssVar: "--font-noto-serif",
  },
  {
    id: "roboto-slab",
    label: "Roboto Slab",
    family: "Roboto Slab",
    type: "serif",
    value: "'Roboto Slab', serif",
    cssVar: "--font-roboto-slab",
  },
  {
    id: "merriweather",
    label: "Merriweather",
    family: "Merriweather",
    type: "serif",
    value: "'Merriweather', serif",
    cssVar: "--font-merriweather",
  },
  {
    id: "lora",
    label: "Lora",
    family: "Lora",
    type: "serif",
    value: "'Lora', serif",
    cssVar: "--font-lora",
  },
] as const;

export type TypesetFont = (typeof TYPESET_FONTS)[number];

export function findTypesetFont(id: string | null | undefined) {
  return TYPESET_FONTS.find((font) => font.id === id);
}
