export default [
  {
    name: "Accordion",
    value: "accordion",
    files: [
      "Accordion/Accordion.vue",
      "Accordion/Content.vue",
      "Accordion/Header.vue",
      "Accordion/Item.vue",
      "Accordion/Trigger.vue",
    ],
    docsPath: "/components/accordion",
  },
  {
    name: "Alert",
    value: "alert",
    files: ["Alert/Alert.vue", "Alert/Description.vue", "Alert/Title.vue"],
    docsPath: "/components/alert",
  },
  {
    name: "Alert Dialog",
    value: "alert-dialog",
    components: ["button"],
    utils: ["translucent.ts"],
    files: [
      "AlertDialog/Action.vue",
      "AlertDialog/AlertDialog.vue",
      "AlertDialog/Cancel.vue",
      "AlertDialog/Content.vue",
      "AlertDialog/Description.vue",
      "AlertDialog/Footer.vue",
      "AlertDialog/Header.vue",
      "AlertDialog/Media.vue",
      "AlertDialog/Overlay.vue",
      "AlertDialog/Portal.vue",
      "AlertDialog/Title.vue",
      "AlertDialog/Trigger.vue",
    ],
    docsPath: "/components/alertdialog",
  },
  {
    name: "Animated Tooltip",
    value: "animated-tooltip",
    files: ["AnimatedTooltip.vue"],
    docsPath: "/components/animatedtooltip",
  },
  {
    name: "Aspect Ratio",
    value: "aspect-ratio",
    files: ["AspectRatio.vue"],
    docsPath: "/components/aspectratio",
  },
  {
    name: "Autocomplete",
    value: "autocomplete",
    files: [
      "Autocomplete/Anchor.vue",
      "Autocomplete/Arrow.vue",
      "Autocomplete/Autocomplete.vue",
      "Autocomplete/Cancel.vue",
      "Autocomplete/Content.vue",
      "Autocomplete/Empty.vue",
      "Autocomplete/Group.vue",
      "Autocomplete/Input.vue",
      "Autocomplete/Item.vue",
      "Autocomplete/ItemIndicator.vue",
      "Autocomplete/Label.vue",
      "Autocomplete/Portal.vue",
      "Autocomplete/Separator.vue",
      "Autocomplete/Trigger.vue",
      "Autocomplete/Viewport.vue",
    ],
    docsPath: "/components/autocomplete",
  },
  {
    name: "Avatar",
    value: "avatar",
    files: [
      "Avatar/Avatar.vue",
      "Avatar/Fallback.vue",
      "Avatar/Image.vue",
      "Avatar/Badge.vue",
      "Avatar/Group.vue",
      "Avatar/GroupCount.vue",
    ],
    docsPath: "/components/avatar",
  },
  {
    name: "Avatar Label Group",
    value: "avatar-label-group",
    files: ["AvatarLabelGroup.vue"],
    components: ["avatar"],
    docsPath: "/components/avatar",
  },
  { name: "Badge", value: "badge", files: ["Badge.vue"], docsPath: "/components/badge" },
  {
    name: "Badge Group",
    value: "badge-group",
    files: ["BadgeGroup.vue"],
    docsPath: "/components/badge-group",
  },
  {
    name: "BG Pattern - Circle",
    value: "bg-pattern-circle",
    files: ["BgPattern/Circle.vue"],
    docsPath: "/components/bg-pattern-circle",
  },
  {
    name: "BG Pattern - Square",
    value: "bg-pattern-square",
    files: ["BgPattern/Square.vue"],
    docsPath: "/components/bg-pattern-square",
  },
  {
    name: "BG Pattern - Grid",
    value: "bg-pattern-grid",
    files: ["BgPattern/Grid.vue"],
    docsPath: "/components/bg-pattern-grid",
  },
  {
    name: "Border Beam",
    value: "border-beam",
    files: ["BorderBeam.vue"],
    docsPath: "/goodies/border-beam",
  },
  {
    name: "Breadcrumbs",
    value: "breadcrumbs",
    files: ["Breadcrumbs.vue"],
    docsPath: "/components/breadcrumbs",
  },
  { name: "Button", value: "button", files: ["Button.vue"], docsPath: "/components/button" },
  {
    name: "Button Group",
    value: "button-group",
    files: ["ButtonGroup/ButtonGroup.vue", "ButtonGroup/Separator.vue", "ButtonGroup/Text.vue"],
    components: ["button", "separator"],
    docsPath: "/components/button-group",
  },
  {
    name: "Calendar",
    value: "calendar",
    devDeps: ["@yuta-inoue-ph/nuxt-vcalendar"],
    nuxtModules: ["@yuta-inoue-ph/nuxt-vcalendar"],
    instructions: [
      "You can customize the calendar by adding options to your nuxt.config.js file",
      "Remember to update your Tailwind CSS reference path for the Calendar component.",
    ],
    files: ["Calendar.vue"],
    docsPath: "/components/calendar",
  },
  {
    name: "Card",
    value: "card",
    files: [
      "Card/Action.vue",
      "Card/Card.vue",
      "Card/Content.vue",
      "Card/Description.vue",
      "Card/Footer.vue",
      "Card/Header.vue",
      "Card/Title.vue",
    ],
    docsPath: "/components/card",
  },
  {
    name: "Carousel",
    value: "carousel",
    files: [
      "Carousel/Carousel.vue",
      "Carousel/Content.vue",
      "Carousel/Item.vue",
      "Carousel/Next.vue",
      "Carousel/Previous.vue",
    ],
    components: ["button"],
    deps: ["embla-carousel-vue", "embla-carousel"],
    composables: ["useCarousel.ts"],
    docsPath: "/components/carousel",
  },
  {
    name: "Checkbox",
    value: "checkbox",
    files: ["Checkbox/Checkbox.vue", "Checkbox/Indicator.vue", "Checkbox/Group.vue"],
    docsPath: "/components/checkbox",
  },
  { name: "Chip", value: "chip", files: ["Chip.vue"], docsPath: "/components/chip" },
  {
    name: "Credit Card",
    value: "credit-card",
    files: ["CreditCard.vue"],
    docsPath: "/components/creditcard",
  },
  {
    name: "Collapsible",
    value: "collapsible",
    files: ["Collapsible/Collapsible.vue", "Collapsible/Content.vue", "Collapsible/Trigger.vue"],
    docsPath: "/components/collapsible",
  },
  {
    name: "Color Picker",
    value: "color-picker",
    files: [
      "ColorPicker/Alpha.vue",
      "ColorPicker/ColorPicker.vue",
      "ColorPicker/Controls.vue",
      "ColorPicker/Hue.vue",
      "ColorPicker/Presets.vue",
      "ColorPicker/Root.vue",
      "ColorPicker/SV.vue",
    ],
    docsPath: "/components/color-picker",
    utils: ["color-picker.context.ts"],
    components: ["select", "input"],
    deps: ["colord"],
  },
  {
    name: "Command",
    value: "command",
    components: ["dialog"],
    files: [
      "Command/Command.vue",
      "Command/Dialog.vue",
      "Command/Empty.vue",
      "Command/Group.vue",
      "Command/Input.vue",
      "Command/Item.vue",
      "Command/List.vue",
      "Command/Separator.vue",
      "Command/Shortcut.vue",
    ],
    docsPath: "/components/command",
  },
  {
    name: "Container",
    value: "container",
    files: ["Container.vue"],
    docsPath: "/components/container",
  },
  {
    name: "Context Menu",
    value: "context-menu",
    utils: ["translucent.ts"],
    files: [
      "ContextMenu/Arrow.vue",
      "ContextMenu/CheckboxItem.vue",
      "ContextMenu/Content.vue",
      "ContextMenu/ContextMenu.vue",
      "ContextMenu/Group.vue",
      "ContextMenu/Item.vue",
      "ContextMenu/ItemIndicator.vue",
      "ContextMenu/Label.vue",
      "ContextMenu/Portal.vue",
      "ContextMenu/RadioGroup.vue",
      "ContextMenu/RadioItem.vue",
      "ContextMenu/Separator.vue",
      "ContextMenu/Shortcut.vue",
      "ContextMenu/Sub.vue",
      "ContextMenu/SubContent.vue",
      "ContextMenu/SubTrigger.vue",
      "ContextMenu/Trigger.vue",
    ],
    docsPath: "/components/contextmenu",
  },
  {
    name: "Currency Input",
    value: "currency-input",
    deps: ["vue-currency-input"],
    files: ["CurrencyInput.vue"],
    docsPath: "/components/currencyinput",
  },
  {
    name: "DataTables.net",
    value: "datatable",
    deps: [
      "datatables.net-buttons-dt",
      "datatables.net-responsive-dt",
      "datatables.net-searchbuilder-dt",
      "datatables.net-select-dt",
      "datatables.net-fixedcolumns-dt",
      "datatables.net-fixedheader-dt",
      "datatables.net-colreorder-dt",
      "datatables.net-vue3",
      "jszip",
    ],
    files: ["Datatable.client.vue"],
    instructions: [
      "Remember to update your Tailwind CSS reference path for the Datatable component.",
    ],
    docsPath: "/components/datatable",
  },
  {
    name: "Date Field",
    value: "date-field",
    deps: ["@internationalized/date"],
    files: ["DateField.vue"],
    docsPath: "/components/datefield",
  },
  {
    name: "Datepicker",
    value: "datepicker",
    devDeps: ["@yuta-inoue-ph/nuxt-vcalendar"],
    nuxtModules: ["@yuta-inoue-ph/nuxt-vcalendar"],
    instructions: [
      "You can customize the datepicker by adding options to your nuxt.config.js file",
      "Remember to update your Tailwind CSS reference path for the Datepicker component.",
    ],
    files: ["Datepicker.vue"],
    docsPath: "/components/datepicker",
  },
  {
    name: "Description List",
    value: "description-list",
    files: [
      "DescriptionList/DescriptionList.vue",
      "DescriptionList/Details.vue",
      "DescriptionList/Term.vue",
    ],
    docsPath: "/components/description-list",
  },
  {
    name: "Dialog",
    value: "dialog",
    utils: ["translucent.ts"],
    files: [
      "Dialog/Close.vue",
      "Dialog/Content.vue",
      "Dialog/Description.vue",
      "Dialog/Dialog.vue",
      "Dialog/Footer.vue",
      "Dialog/Header.vue",
      "Dialog/Overlay.vue",
      "Dialog/Portal.vue",
      "Dialog/Title.vue",
      "Dialog/Trigger.vue",
    ],
    docsPath: "/components/dialog",
  },
  {
    name: "Divider",
    value: "divider",
    components: ["avatar"],
    files: ["Divider.vue"],
    docsPath: "/components/divider",
  },
  {
    name: "Draggable",
    value: "draggable",
    deps: ["vuedraggable@next"],
    files: ["Draggable.vue"],
    docsPath: "/components/draggable",
  },
  {
    name: "Drawer",
    value: "drawer",
    deps: ["vaul-vue"],
    utils: ["translucent.ts"],
    files: [
      "Drawer/Close.vue",
      "Drawer/Content.vue",
      "Drawer/Description.vue",
      "Drawer/Drawer.vue",
      "Drawer/Footer.vue",
      "Drawer/Header.vue",
      "Drawer/Overlay.vue",
      "Drawer/Portal.vue",
      "Drawer/Title.vue",
      "Drawer/Trigger.vue",
    ],
    docsPath: "/components/drawer",
  },
  {
    name: "Dropdown Menu",
    value: "dropdown-menu",
    utils: ["translucent.ts"],
    files: [
      "DropdownMenu/Arrow.vue",
      "DropdownMenu/CheckboxItem.vue",
      "DropdownMenu/Content.vue",
      "DropdownMenu/DropdownMenu.vue",
      "DropdownMenu/Group.vue",
      "DropdownMenu/Item.vue",
      "DropdownMenu/ItemIndicator.vue",
      "DropdownMenu/Label.vue",
      "DropdownMenu/Portal.vue",
      "DropdownMenu/RadioGroup.vue",
      "DropdownMenu/RadioItem.vue",
      "DropdownMenu/Separator.vue",
      "DropdownMenu/Shortcut.vue",
      "DropdownMenu/Sub.vue",
      "DropdownMenu/SubContent.vue",
      "DropdownMenu/SubTrigger.vue",
      "DropdownMenu/Trigger.vue",
    ],
    docsPath: "/components/dropdownmenu",
  },
  {
    name: "Dropfile",
    value: "dropfile",
    files: ["Dropfile.vue"],
    docsPath: "/components/dropfile",
  },
  {
    name: "Editable",
    value: "editable",
    files: [
      "Editable/Area.vue",
      "Editable/Cancel.vue",
      "Editable/Edit.vue",
      "Editable/Editable.vue",
      "Editable/Input.vue",
      "Editable/Preview.vue",
      "Editable/Submit.vue",
    ],
    docsPath: "/components/editable",
  },
  {
    name: "Empty",
    value: "empty",
    files: [
      "Empty/Content.vue",
      "Empty/Description.vue",
      "Empty/Empty.vue",
      "Empty/Header.vue",
      "Empty/Media.vue",
      "Empty/Title.vue",
    ],
    docsPath: "/components/empty",
  },
  {
    name: "Fancy Icon",
    value: "fancy-icon",
    files: ["FancyIcon.vue"],
    docsPath: "/components/fancyicon",
  },
  {
    name: "Field",
    value: "field",
    files: [
      "Field/Content.vue",
      "Field/Description.vue",
      "Field/Error.vue",
      "Field/Field.vue",
      "Field/Group.vue",
      "Field/Label.vue",
      "Field/Legend.vue",
      "Field/Separator.vue",
      "Field/Set.vue",
      "Field/Title.vue",
    ],
    components: ["label", "separator"],
    docsPath: "/components/field",
  },
  {
    name: "Flick Clock",
    value: "flip-clock",
    files: ["FlipClock.client.vue"],
    docsPath: "/components/flip-clock",
  },
  {
    name: "Form",
    value: "form",
    deps: ["@vee-validate/nuxt"],
    nuxtModules: ["@vee-validate/nuxt"],
    composables: ["useFormField.ts"],
    files: [
      "Form/Control.vue",
      "Form/Description.vue",
      "Form/Item.vue",
      "Form/Label.vue",
      "Form/Message.vue",
    ],
    docsPath: "/components/form",
  },
  {
    name: "Floating Dock",
    value: "floating-dock",
    files: ["FloatingDock.vue"],
    docsPath: "/components/floating-dock",
  },
  {
    name: "Gradient Divider",
    value: "gradient-divider",
    files: ["GradientDivider.vue"],
    docsPath: "/goodies/gradient-divider",
  },
  {
    name: "Heading",
    value: "heading",
    files: ["Heading.vue"],
    docsPath: "/components/heading",
  },
  {
    name: "Hover Card",
    value: "hover-card",
    utils: ["translucent.ts"],
    files: [
      "HoverCard/Arrow.vue",
      "HoverCard/Content.vue",
      "HoverCard/HoverCard.vue",
      "HoverCard/Portal.vue",
      "HoverCard/Trigger.vue",
    ],
    docsPath: "/components/hovercard",
  },
  {
    name: "Icon",
    value: "icon",
    files: ["Icon.vue"],
    docsPath: "/components/icon",
  },
  {
    name: "Iframe (Lazy)",
    value: "iframe-lazy",
    files: ["IframeLazy.vue"],
    docsPath: "/components/iframelazy",
  },
  {
    name: "Input",
    value: "input",
    files: ["Input.vue"],
    docsPath: "/components/input",
  },
  {
    name: "Input Group",
    value: "input-group",
    files: [
      "InputGroup/Addon.vue",
      "InputGroup/Button.vue",
      "InputGroup/Input.vue",
      "InputGroup/InputGroup.vue",
      "InputGroup/Text.vue",
      "InputGroup/Textarea.vue",
    ],
    components: ["input", "button", "textarea"],
    docsPath: "/components/input-group",
  },
  {
    name: "Item",
    value: "item",
    files: [
      "Item/Actions.vue",
      "Item/Content.vue",
      "Item/Description.vue",
      "Item/Footer.vue",
      "Item/Group.vue",
      "Item/Header.vue",
      "Item/Item.vue",
      "Item/Media.vue",
      "Item/Separator.vue",
      "Item/Title.vue",
    ],
    components: ["separator"],
    docsPath: "/components/item",
  },
  {
    name: "Keyboard Key",
    value: "kbd",
    files: ["Kbd/Kbd.vue", "Kbd/Group.vue"],
    docsPath: "/components/keyboardkey",
  },
  {
    name: "Label",
    value: "label",
    files: ["Label.vue"],
    docsPath: "/components/label",
  },
  {
    name: "List",
    value: "list",
    files: [
      "List/Content.vue",
      "List/Item.vue",
      "List/List.vue",
      "List/Subtitle.vue",
      "List/Title.vue",
    ],
    docsPath: "/components/list",
  },
  {
    name: "Listbox",
    value: "listbox",
    files: [
      "Listbox/Content.vue",
      "Listbox/Filter.vue",
      "Listbox/Group.vue",
      "Listbox/GroupLabel.vue",
      "Listbox/Item.vue",
      "Listbox/ItemIndicator.vue",
      "Listbox/Listbox.vue",
      "Listbox/Virtualizer.vue",
    ],
    docsPath: "/components/listbox",
  },
  {
    name: "Loader",
    value: "loader",
    files: ["Loader.vue"],
    devDeps: ["@iconify-json/svg-spinners"],
    docsPath: "/components/loader",
  },
  {
    name: "Menubar",
    value: "menubar",
    utils: ["translucent.ts"],
    files: [
      "Menubar/Arrow.vue",
      "Menubar/CheckboxItem.vue",
      "Menubar/Content.vue",
      "Menubar/Group.vue",
      "Menubar/Item.vue",
      "Menubar/ItemIndicator.vue",
      "Menubar/Label.vue",
      "Menubar/Menu.vue",
      "Menubar/Menubar.vue",
      "Menubar/Portal.vue",
      "Menubar/RadioGroup.vue",
      "Menubar/RadioItem.vue",
      "Menubar/Separator.vue",
      "Menubar/Shortcut.vue",
      "Menubar/Sub.vue",
      "Menubar/SubContent.vue",
      "Menubar/SubTrigger.vue",
      "Menubar/Trigger.vue",
    ],
    docsPath: "/components/menubar",
  },
  {
    name: "Nav",
    value: "nav",
    files: [
      "Nav/Gap.vue",
      "Nav/Inset.vue",
      "Nav/Item.vue",
      "Nav/Label.vue",
      "Nav/Mobile.vue",
      "Nav/Nav.vue",
      "Nav/Provider.vue",
      "Nav/Section.vue",
      "Nav/Separator.vue",
      "Nav/Spacer.vue",
      "Nav/Start.vue",
      "Nav/Trigger.vue",
    ],
    components: ["separator", "sheet", "button"],
    docsPath: "/components/nav",
  },
  {
    name: "Navbar",
    value: "navbar",
    files: ["Navbar.vue"],
    docsPath: "/components/navbar",
  },
  {
    name: "Native Select",
    value: "native-select",
    files: ["NativeSelect.vue"],
    docsPath: "/components/select-native",
  },
  {
    name: "Navigation Menu",
    value: "navigation-menu",
    files: [
      "NavigationMenu/Content.vue",
      "NavigationMenu/Indicator.vue",
      "NavigationMenu/Item.vue",
      "NavigationMenu/Link.vue",
      "NavigationMenu/List.vue",
      "NavigationMenu/NavigationMenu.vue",
      "NavigationMenu/Sub.vue",
      "NavigationMenu/Trigger.vue",
      "NavigationMenu/Viewport.vue",
    ],
    docsPath: "/components/navigationmenu",
  },
  {
    name: "Number Field",
    value: "number-field",
    deps: ["@internationalized/number"],
    files: [
      "NumberField/Decrement.vue",
      "NumberField/Increment.vue",
      "NumberField/Input.vue",
      "NumberField/NumberField.vue",
    ],
    docsPath: "/components/number-field",
  },
  {
    name: "Pagination",
    value: "pagination",
    files: [
      "Pagination/Ellipsis.vue",
      "Pagination/First.vue",
      "Pagination/Item.vue",
      "Pagination/Last.vue",
      "Pagination/List.vue",
      "Pagination/Next.vue",
      "Pagination/Pagination.vue",
      "Pagination/Prev.vue",
    ],
    components: ["button"],
    docsPath: "/components/pagination",
  },
  {
    name: "Pin Input (OTP)",
    value: "pin-input",
    files: ["PinInput/PinInput.vue", "PinInput/PinInputInput.vue", "PinInput/Group.vue"],
    docsPath: "/components/pininput",
  },
  {
    name: "Placeholder",
    value: "placeholder",
    files: ["Placeholder.vue"],
    docsPath: "/components/placeholder",
  },
  {
    name: "Popover",
    value: "popover",
    utils: ["translucent.ts"],
    files: [
      "Popover/Anchor.vue",
      "Popover/Arrow.vue",
      "Popover/Close.vue",
      "Popover/Content.vue",
      "Popover/Popover.vue",
      "Popover/Portal.vue",
      "Popover/Trigger.vue",
      "Popover/X.vue",
    ],
    docsPath: "/components/popover",
  },
  {
    name: "Pointer Highlight",
    value: "pointer-highlight",
    files: ["PointerHighlight.vue"],
    docsPath: "/components/pointer-highlight",
  },
  {
    name: "Progress",
    value: "progress",
    files: ["Progress/Indicator.vue", "Progress/Progress.vue"],
    docsPath: "/components/progress",
  },
  {
    name: "QR Code",
    value: "qrcode",
    files: ["QRCode/QRCode.vue", "QRCode/FrameHandle.vue", "QRCode/GradientScan.vue"],
    docsPath: "/components/qrcode",
  },
  {
    name: "Radio Group",
    value: "radio-group",
    files: ["RadioGroup/Indicator.vue", "RadioGroup/Item.vue", "RadioGroup/RadioGroup.vue"],
    docsPath: "/components/radiogroup",
  },
  {
    name: "Rating",
    value: "rating",
    files: ["Rating.vue"],
    docsPath: "/components/rating",
  },
  {
    name: "Scroll Area",
    value: "scroll-area",
    files: [
      "ScrollArea/Corner.vue",
      "ScrollArea/ScrollArea.vue",
      "ScrollArea/Scrollbar.vue",
      "ScrollArea/Thumb.vue",
      "ScrollArea/Viewport.vue",
    ],
    docsPath: "/components/scrollarea",
  },
  {
    name: "Scrollspy",
    value: "scrollspy",
    files: ["Scrollspy.vue"],
    composables: ["useScrollspy.ts"],
    docsPath: "/components/scrollspy",
  },
  {
    name: "Select",
    value: "select",
    utils: ["translucent.ts"],
    files: [
      "Select/Arrow.vue",
      "Select/Content.vue",
      "Select/Group.vue",
      "Select/Icon.vue",
      "Select/Item.vue",
      "Select/ItemIndicator.vue",
      "Select/ItemText.vue",
      "Select/Label.vue",
      "Select/Portal.vue",
      "Select/ScrollDownButton.vue",
      "Select/ScrollUpButton.vue",
      "Select/Select.vue",
      "Select/Separator.vue",
      "Select/Trigger.vue",
      "Select/Value.vue",
      "Select/Viewport.vue",
    ],
    docsPath: "/components/select",
  },
  {
    name: "Separator",
    value: "separator",
    files: ["Separator.vue"],
    docsPath: "/components/separator",
  },
  {
    name: "Sheet",
    value: "sheet",
    utils: ["translucent.ts"],
    files: [
      "Sheet/Close.vue",
      "Sheet/Content.vue",
      "Sheet/Description.vue",
      "Sheet/Footer.vue",
      "Sheet/Header.vue",
      "Sheet/Overlay.vue",
      "Sheet/Portal.vue",
      "Sheet/Sheet.vue",
      "Sheet/Title.vue",
      "Sheet/Trigger.vue",
      "Sheet/X.vue",
    ],
    docsPath: "/components/sheet",
  },
  {
    name: "Sidebar",
    value: "sidebar",
    files: [
      "Sidebar/Content.vue",
      "Sidebar/Footer.vue",
      "Sidebar/Group.vue",
      "Sidebar/GroupAction.vue",
      "Sidebar/GroupContent.vue",
      "Sidebar/GroupLabel.vue",
      "Sidebar/Header.vue",
      "Sidebar/Input.vue",
      "Sidebar/Inset.vue",
      "Sidebar/Menu.vue",
      "Sidebar/MenuAction.vue",
      "Sidebar/MenuBadge.vue",
      "Sidebar/MenuButton.vue",
      "Sidebar/MenuButtonChild.vue",
      "Sidebar/MenuItem.vue",
      "Sidebar/MenuSkeleton.vue",
      "Sidebar/MenuSub.vue",
      "Sidebar/MenuSubButton.vue",
      "Sidebar/MenuSubItem.vue",
      "Sidebar/Provider.vue",
      "Sidebar/Rail.vue",
      "Sidebar/Separator.vue",
      "Sidebar/Sidebar.vue",
      "Sidebar/Trigger.vue",
    ],
    components: ["input", "tooltip", "skeleton", "separator", "sheet", "button"],
    utils: ["sidebar.ts"],
    docsPath: "/components/sidebar",
  },
  {
    name: "Skeleton",
    value: "skeleton",
    files: ["Skeleton.vue"],
    docsPath: "/components/skeleton",
  },
  {
    name: "Slider",
    value: "slider",
    files: ["Slider/Range.vue", "Slider/Slider.vue", "Slider/Thumb.vue", "Slider/Track.vue"],
    docsPath: "/components/slider",
  },
  {
    name: "Sonner",
    value: "sonner",
    deps: ["vue-sonner"],
    instructions: ["Remember to add the <UiSonner /> tag to your app.vue/layout file."],
    nuxtModules: ["vue-sonner/nuxt"],
    files: ["Sonner.vue"],
    docsPath: "/components/sonner",
  },
  {
    name: "Splitter",
    value: "splitter",
    files: ["Splitter/Splitter.vue", "Splitter/Panel.vue", "Splitter/Handle.vue"],
    docsPath: "/components/splitter",
  },
  {
    name: "Stepper",
    value: "stepper",
    files: [
      "Stepper/Description.vue",
      "Stepper/Indicator.vue",
      "Stepper/Item.vue",
      "Stepper/Separator.vue",
      "Stepper/Stepper.vue",
      "Stepper/Title.vue",
      "Stepper/Trigger.vue",
    ],
    docsPath: "/components/stepper",
  },
  {
    name: "Switch",
    value: "switch",
    files: ["Switch/Switch.vue", "Switch/Thumb.vue"],
    docsPath: "/components/switch",
  },
  {
    name: "Table",
    value: "table",
    files: [
      "Table/Body.vue",
      "Table/Caption.vue",
      "Table/Cell.vue",
      "Table/Empty.vue",
      "Table/Footer.vue",
      "Table/Head.vue",
      "Table/Header.vue",
      "Table/Row.vue",
      "Table/Table.vue",
    ],
    docsPath: "/components/table",
  },
  {
    name: "Tabs",
    value: "tabs",
    files: [
      "Tabs/Content.vue",
      "Tabs/Indicator.vue",
      "Tabs/List.vue",
      "Tabs/Tabs.vue",
      "Tabs/Trigger.vue",
    ],
    docsPath: "/components/tabs",
  },
  {
    name: "Tags Input",
    value: "tags-input",
    files: [
      "TagsInput/Clear.vue",
      "TagsInput/Item.vue",
      "TagsInput/ItemDelete.vue",
      "TagsInput/ItemText.vue",
      "TagsInput/TagsInput.vue",
      "TagsInput/TagsInputInput.vue",
    ],
    docsPath: "/components/tagsinput",
  },
  {
    name: "Tanstack Table",
    value: "tanstacktable",
    deps: ["@tanstack/vue-table"],
    components: ["tooltip", "dropdown-menu", "table", "button", "select"],
    files: ["TanStackTable.vue"],
    docsPath: "/components/tanstacktable",
  },
  {
    name: "Terminal",
    value: "terminal",
    files: ["Terminal/AnimatedSpan.vue", "Terminal/Terminal.vue", "Terminal/TypingAnimation.vue"],
    docsPath: "/goodies/terminal",
  },
  {
    name: "Textarea",
    value: "textarea",
    files: ["Textarea.vue"],
    docsPath: "/components/textarea",
  },
  {
    name: "Timeline",
    value: "timeline",
    files: [
      "Timeline/Content.vue",
      "Timeline/Date.vue",
      "Timeline/Header.vue",
      "Timeline/Indicator.vue",
      "Timeline/Item.vue",
      "Timeline/Separator.vue",
      "Timeline/Timeline.vue",
      "Timeline/Title.vue",
    ],
    docsPath: "/components/timeline",
  },
  {
    name: "Toggle",
    value: "toggle",
    files: ["Toggle.vue"],
    docsPath: "/components/toggle",
  },
  {
    name: "Toggle Group",
    value: "toggle-group",
    components: ["toggle"],
    files: ["ToggleGroup/ToggleGroup.vue", "ToggleGroup/ToggleGroupItem.vue"],
    docsPath: "/components/togglegroup",
  },
  {
    name: "Tooltip",
    value: "tooltip",
    files: [
      "Tooltip/Arrow.vue",
      "Tooltip/Content.vue",
      "Tooltip/Portal.vue",
      "Tooltip/Provider.vue",
      "Tooltip/Tooltip.vue",
      "Tooltip/Trigger.vue",
    ],
    docsPath: "/components/tooltip",
  },
  {
    name: "Tree",
    value: "tree",
    files: ["Tree/Item.vue", "Tree/Tree.vue", "Tree/Virtualizer.vue"],
    docsPath: "/components/tree",
  },
  {
    name: "Vee Form Builder",
    value: "vee-form-builder",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: [
      "label",
      "vee-checkbox",
      "vee-switch",
      "Vee-input",
      "divider",
      "vee-currency-input",
      "vee-date-field",
      "vee-textarea",
      "vee-file-input",
      "vee-multi-select",
      "vee-select",
      "vee-pin-input",
      "vee-tags-input",
      "vee-radio-group",
      "vee-vue-form-slider",
      "vee-native-checkbox",
    ],
    files: ["FormBuilder/FormBuilder.vue"],
    docsPath: "/forms/form-builder",
  },
  {
    name: "Vee VueFormSlider",
    value: "vee-vue-form-slider",
    deps: ["@vee-validate/nuxt", "@vueform/slider"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: [],
    files: ["Vee/VueFormSlider.vue"],
    docsPath: "/forms/vee-vueformslider",
  },
  {
    name: "Vee Checkbox",
    value: "vee-checkbox",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["checkbox", "label"],
    files: ["Vee/Checkbox.vue"],
    docsPath: "/forms/veecheckbox",
  },
  {
    name: "Vee Switch",
    value: "vee-switch",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["switch", "label"],
    files: ["Vee/Switch.vue"],
    docsPath: "/forms/veeswitch",
  },
  {
    name: "Vee Checkbox - Native",
    value: "vee-native-checkbox",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["label"],
    files: ["Vee/NativeCheckbox.vue"],
    docsPath: "/forms/veecheckbox-native",
  },
  {
    name: "Vee CurrencyInput",
    value: "vee-currency-input",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["currency-input", "label"],
    files: ["Vee/CurrencyInput.vue"],
    docsPath: "/forms/veecurrencyinput",
  },
  {
    name: "Vee DateField",
    value: "vee-date-field",
    deps: ["@vee-validate/nuxt", "@internationalized/date"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["date-field", "label"],
    files: ["Vee/DateField.vue"],
    docsPath: "/forms/veedatefield",
  },
  {
    name: "Vee Datepicker",
    value: "vee-datepicker",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["datepicker", "label", "input"],
    files: ["Vee/Datepicker.vue"],
    docsPath: "/forms/veedatepicker",
  },
  {
    name: "Vee FileInput",
    value: "vee-file-input",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["input", "label"],
    files: ["Vee/FileInput.vue"],
    docsPath: "/forms/veefileinput",
  },
  {
    name: "Vee Input",
    value: "vee-input",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["input", "label"],
    files: ["Vee/Input.vue"],
    docsPath: "/forms/veeinput",
  },
  {
    name: "Vee MultiSelect",
    value: "vee-multi-select",
    deps: ["@vee-validate/nuxt", "@vueform/multiselect"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["label"],
    files: ["Vee/MultiSelect.vue"],
    docsPath: "/forms/veemultiselect",
  },
  {
    name: "Vee NumberField",
    value: "vee-number-field",
    deps: ["@vee-validate/nuxt", "@internationalized/number"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["label", "number-field"],
    files: ["Vee/NumberField.vue"],
    docsPath: "/forms/veenumberfield",
  },
  {
    name: "Vee Pin-Input",
    value: "vee-pin-input",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["label", "pin-input"],
    files: ["Vee/PinInput.vue"],
    docsPath: "/forms/veepininput",
  },
  {
    name: "Vee RadioGroup",
    value: "vee-radio-group",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["radio-group", "label"],
    files: ["Vee/RadioGroup.vue"],
    docsPath: "/forms/veeradiogroup",
  },
  {
    name: "Vee Select",
    value: "vee-select",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["native-select", "label"],
    files: ["Vee/Select.vue"],
    docsPath: "/forms/veeselect",
  },
  {
    name: "Vee Tags-Input",
    value: "vee-tags-input",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["tags-input", "label"],
    files: ["Vee/TagsInput.vue"],
    docsPath: "/forms/veetagsinput",
  },
  {
    name: "Vee Textarea",
    value: "vee-textarea",
    deps: ["@vee-validate/nuxt"],
    askValidator: true,
    nuxtModules: ["@vee-validate/nuxt"],
    components: ["textarea", "label"],
    files: ["Vee/Textarea.vue"],
    docsPath: "/forms/veetextarea",
  },
  {
    name: "Apexcharts",
    value: "apexcharts",
    deps: ["apexcharts", "vue3-apexcharts"],
    components: ["card"],
    files: ["Apexchart.client.vue"],
    docsPath: "/apex-charts",
  },
  {
    name: "Neon Gradient Card",
    value: "neon-gradient-card",
    files: ["NeonGradientCard.vue"],
    docsPath: "/goodies/neon-gradient-card",
  },
  {
    name: "Retro Grid",
    value: "retro-grid",
    files: ["RetroGrid.vue"],
    docsPath: "/goodies/retro-grid",
  },
];
